!
! TWO-REACTION TEST CASE
! ZDPLASKIN
!
! This test case corresponds to an Ar plasma consisting of electrons, atomic
! ions, and neutrals. The charged particles are supposed to be generated by
! direct electron impact ionization and lost by 3-body recombination.
!
! June 2008, by S Pancheshnyi
!

subroutine zdpSolver_init(nBolsigReactions, nBolsigSpecies, speciesName, reactionName, parameters)
!
! declare variables and modules
!
use options
use ZDPlasKin
integer::nBolsigReactions
character*8::speciesName(200)
character*20::reactionName(200)
real(kind=8)::parameters(20)
! initialization of ZDPlasKin
!
  call set_parameters()     ! read and set the parameters defined in the condition.ini file	    

  parameters(2)=gas_pressure ! pressure (torr)
  parameters(3)=voltage  ! external voltage (V)
  parameters(4)=resistance  ! external resistance (Ohm)
  parameters(5)=gap_length ! gap length (cm)
  parameters(6)=radius ! plasma channel radius (cm)
  parameters(7)=gap_area ! (cm2) = 3.1415*radius**2
  parameters(8)=gas_temperature ! gas temperature (K)
  parameters(9)=gas_density ! gas density (cm-3) = 1.0d-6 * ( 101325.0d0 * gas_pressure / 760.0d0 ) / ( 1.38065d-23 * gas_temperature )
  parameters(10)=elec_density  ! initial electron density (cm-3)
  parameters(11)=time_end ! end of calculations (s)

  parameters(1) = 1.0d17*parameters(3)/(parameters(5)*parameters(9))   !reduced electric field: EN = 1.0d17*voltage/(gap_length*gas_density) 

  call ZDPlasKin_init()
  nBolsigReactions = reactions_max
  nBolsigSpecies = species_max

  do i = 1, species_max
    speciesName(i)=species_name(i)
  enddo

  do i = 1, reactions_max
    reactionName(i)=reaction_sign(i)
  enddo

  
  ! Tells Bolsig the value of the reduced field (to do each time EN changes)
  call ZDPlasKin_set_conditions(REDUCED_FIELD=parameters(1))
  T_old = -1.0
  EN_old = -1.0
end


subroutine zdpSolver(parameters, Arate)
!
! declare variables and modules
!
  use options
  use ZDPlasKin
  implicit none
  real(kind=8)::Arate(reactions_max)
  real(kind=8)::parameters(20)
  integer:: i
!  double precision, parameter :: gas_temperature  = 301.0d0, & ! gas temperature, K
!                                 reduced_field    = 51.0d0,  & ! reduced electric field, Td
!                                 density_ini_ar   = 2.5d19,  & ! initial Ar density, cm-3
!                                 density_ini_elec = 1.0d0      ! initial electron density, cm-3
!  double precision            :: time  = 0.0d0, time_end = 3.0d-7, dtime = 1.0d-8 ! times, s


  parameters(1) = 1.0d17*parameters(3)/(parameters(5)*parameters(9))   !1.0d17*voltage/(gap_length*gas_density) 
  if(abs(parameters(8)-T_old)<1.0d-6 .AND. abs(parameters(1)-EN_old)<1.0d-6 )then
  ! write(*,*)"not repeat for the same T and EN."
    return
  endif
  call ZDPlasKin_set_conditions(GAS_TEMPERATURE=parameters(8), REDUCED_FIELD=parameters(1) )
  T_old = parameters(8)
  EN_old = parameters(1)
!
! set initial densities
!
! call ZDPlasKin_set_density(  'Ar',nD(1))
!  call ZDPlasKin_set_density(   'e',nD(2))
!  call ZDPlasKin_set_density('Ar^+',nD(3))

  do i = 1, species_max
    call ZDPlasKin_set_density( species_name(i), 1.0d8)
  enddo

  call ZDPlasKin_reac_rates(0)
  
  do i = 1, reactions_max
    Arate(i)=rrt(i)
  enddo

end
